[package]
name = "js8wait"
version = "0.1.0"
edition = "2021"

[dependencies]
bwavfile = "2.0.1"
chrono = "0.4.39"
clap = { version = "4.5.28", features = ["derive"] }
cpal = "0.15.3"
rodio = "0.20.1"
serde = { version = "1.0.217", features = ["derive"] }

